### ISSUE TITLE
Shutdown on linux

### ISSUE THREAD

**Issue by masavoyat** [masavoyat/MicStreamServer#5]
Server not shutting down properly on linux:

_^CShutting down stream receivers
Shutting down the web server
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
_

**Comment by masavoyat** [comment]
Same behavior with python 3.5 and 3.6 on ubuntu.
Not seen on windows.
